name: umq
description: UMQ APP | SCUBA WORLD
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.3.0+4

environment:
  sdk: '>=3.0.3 <4.0.0'  #flutter sdk 3.10.4
#  sdk: '>=3.0.5 <4.0.0'  #flutter sdk 3.10.5


dependencies:
  flutter:
    sdk: flutter

 #+--------------------------------------------------------------- firebase, notification and permission handler

  #firebase 2022-04
  #  firebase_core: ^1.17.0
  #  firebase_analytics: ^9.1.8
  #  firebase_auth: ^3.3.18
  #  firebase_database: ^9.0.14
  #  firebase_messaging: ^11.4.0
  #  firebase_crashlytics: ^2.8.0

  #firebase 2023-03
#  firebase_core: ^2.8.0
#  firebase_analytics: ^10.1.6
#  firebase_auth: ^4.3.0
#  firebase_database: ^10.0.16
#  firebase_messaging: ^14.3.0
#  firebase_crashlytics: ^3.0.17
  #flutter_local_notifications: ^11.0.0  #2023-07  (while try to fix error Because timezone_to_country >=2.1.0 depends on timezone ^0.9.2 and flutter_local_notifications >=9.0.0 <11.0.0 depends on timezone ^0.8.0, )
# permission_handler: ^10.0.0

  firebase_core: ^2.14.0
  # firebase_auth: ^4.6.3
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.4.18
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.1
  clear_all_notifications: ^0.0.3
  permission_handler: ^10.4.1

  #--------------------------------------------------------------- state manager

  provider: ^6.0.5
  need_resume: ^1.0.7+1
  mvc_pattern: ^8.12.0

  #--------------------------------------------------------------- other plugins

  fastor_app_ui_widget: 1.0.255

  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7

  #webservice
  http:
  dio: ^5.3.2
  internet_connection_checker: ^1.0.0+1

  pretty_dio_logger: ^1.3.1

  clipboard: ^0.1.3
  url_launcher: ^6.1.14
  awesome_dialog: ^3.1.0

  #countery code
  country_codes: ^2.2.0
  country_code_picker: ^3.0.0

  #time stamp
  intl: ^0.17.0

  #recorder and audio and file picker
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  path_provider: ^2.1.1
  media_info: ^0.12.0+2
  assets_audio_player: ^3.1.1
  image_picker: ^1.0.4

  #timezone
  timezone_to_country: ^2.1.0
  country_dial_code: ^1.2.0

  #paypal-webview-payment
  flutter_inappwebview: ^5.7.2+3

  #--------------------------------------------------------------- developer

  #dev- amit
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0


  #abdelrahman
  carousel_slider: ^4.1.1
  video_player: ^2.7.1
  chewie: ^1.7.0

  #pull_to_refresh: ^2.0.0
  smooth_star_rating_null_safety: ^1.0.4+2

  #amal
  whatsapp_unilink: ^2.0.1+1
  flutter_phone_direct_caller: ^2.1.0
  uni_links: ^0.5.1
  get: ^4.6.5
  flutter_share: ^2.0.0

  #jas
  #  rxdart: ^0.27.7
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.2.3
  extended_image: ^8.0.2
  mime: ^1.0.4

  #html editior
  quill_html_editor: ^2.2.6
  flutter_widget_from_html: ^0.10.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
#    - assets/example_mobile/
    #    - assets/example_admin/
    - assets/images/
    - assets/fastor/
    - assets/admin/
    - assets/chat/

  fonts:

    - family: FishDemo-1Gmq0
      fonts:
        - asset: assets/font/point/FishDemo-1Gmq0.otf

    - family: Marina Sundaland
      fonts:
        - asset: assets/font/fish/Marina Sundaland.otf

    - family: Mermaid Astramadea
      fonts:
        - asset: assets/font/fish/Mermaid Astramadea.otf

    - family: LifesABeachThin-4Kp6
      fonts:
        - asset: assets/font/beach/LifesABeachThin-4Kp6.ttf

    - family: LifesABeach-gAo5.ttf
      fonts:
        - asset: assets/font/beach/LifesABeach-gAo5.ttf
