// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3bMiE6BEI5hyFQNqw-tJ5K5Fn1hj468w',
    appId: '1:637213655643:web:f2fc7e41b1f79ebcc1357e',
    messagingSenderId: '637213655643',
    projectId: 'scuba-6780c',
    authDomain: 'scuba-6780c.firebaseapp.com',
    databaseURL: 'https://scuba-6780c-default-rtdb.firebaseio.com',
    storageBucket: 'scuba-6780c.appspot.com',
    measurementId: 'G-STWHMMT8JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrWwDoI0NL_hxl7MZg7vDXvk1LQhpvJ_o',
    appId: '1:637213655643:android:558b19b842fcea51c1357e',
    messagingSenderId: '637213655643',
    projectId: 'scuba-6780c',
    databaseURL: 'https://scuba-6780c-default-rtdb.firebaseio.com',
    storageBucket: 'scuba-6780c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAffnlpxjyLB9zFE0_CMAaCJaSFWrlT9eM',
    appId: '1:637213655643:ios:46e2431f94747b0fc1357e',
    messagingSenderId: '637213655643',
    projectId: 'scuba-6780c',
    databaseURL: 'https://scuba-6780c-default-rtdb.firebaseio.com',
    storageBucket: 'scuba-6780c.appspot.com',
    androidClientId: '637213655643-8uc8hk6vssrljima6tk7brg4s6s2rh5i.apps.googleusercontent.com',
    iosClientId: '637213655643-64r2putgvo5shcri68pal3usirko12c6.apps.googleusercontent.com',
    iosBundleId: 'umq.app.umq',
  );
}
